library(ggplot2)
library(forecast)
library(tseries)
library(readxl)
library(lubridate)
elec_train <- read_excel("Full Data.xlsx", sheet = "Training")
elec_train$Transaction_Dates <- elec_train$Transaction_Dates + hours(elec_train$Hours)
hist(elec_train$Day_Ahead_Price)
elec_train$Day_Ahead_Price_log <- log(elec_train$Day_Ahead_Price)
hist(elec_train$Day_Ahead_Price_log)
elec_train$Day_Ahead_Price_ts <- ts(elec_train$Day_Ahead_Price_log)
elec_train$Day_Ahead_Price_ts <- tsclean(elec_train$Day_Ahead_Price_ts)
plot(elec_train$Day_Ahead_Price_ts)
adf.test(elec_train$Day_Ahead_Price_ts, alternative = "stationary")
Acf(elec_train$Day_Ahead_Price_ts, main='')
Pacf(elec_train$Day_Ahead_Price_ts, main='')
elec_train$ma_1 <- ma(elec_train$Day_Ahead_Price_ts, order = 24)
elec_train$ma_2 <- ma(elec_train$Day_Ahead_Price_ts, order = 168)
plot(elec_train$Day_Ahead_Price_ts, col = "red", main = "Moving Average", xlab = "Time", ylab = "Price")
lines(elec_train$ma_1, col="green")
lines(elec_train$ma_2, col="blue")
ar.fit2 <- auto.arima(elec_train$Day_Ahead_Price, seasonal = TRUE)
summary(ar.fit2)
ar.f3 <- forecast(ar.fit2, h = 24)
ar.fitted3 <- data.frame(as.numeric(ar.fit2$fitted))
ar.predict3 <- data.frame(as.numeric(ar.f3$mean))
elec_test <- read_excel("Full Data.xlsx", sheet = "Test")
elec_test_1 <- elec_test[1:24,]
ModelMetrics::rmse(elec_test_1$Day_Ahead_Price,ar.predict3[,1])
plot(ts(elec_test_1$Day_Ahead_Price), col="blue", main = "Actual vs predicted for one day", xlab = "Time", ylab = "Price")
lines(ts(ar.predict3[,1]))
ar.f2 <- forecast(ar.fit2, h=8762)
ar.fitted2 <- data.frame(as.numeric(ar.fit2$fitted)) 
ar.predict2 <- data.frame(as.numeric(ar.f2$mean))
ModelMetrics::rmse(elec_train$Day_Ahead_Price,ar.fitted2[,1])
elec_test <- read_excel("Full Data.xlsx", sheet = "Test")
ModelMetrics::rmse(elec_test$Day_Ahead_Price,ar.predict2[,1])
elec_full <- read_excel("Full Data.xlsx", sheet = "Full_Data")
plot(ar.f2)
plot(ar.f2)
lines(elec_full$`N.Y.C. - J Day Ahead Price`, col="black")
plot(ts(ar.predict2[,1]))
lines(ts(elec_test$Day_Ahead_Price), col="blue", main = "Actual vs predicted for 2016", xlab = "Time", ylab = "Price")
plot(ar.f2,main = "")
tsdisplay(residuals(ar.f2), lag.max=45, main='(4,1,3) Model Residuals')